name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: sudo apt install libgtk-4-dev build-essential
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
